import type {
    ArtaEscalation,
    AuditTrailEntry,
    BottleneckData,
    DashboardStats,
    Department,
    Document,
    DocumentType,
    RoutingSlip,
    SmsNotification,
    StatusDistribution,
    TrackngoUser,
} from '@/types/trackngo';

// ── Mock Departments ────────────────────────────────────────────────
export const mockDepartments: Department[] = [
    { id: 1, name: 'Office of the Mayor', code: 'OOM', is_active: true },
    { id: 2, name: 'Human Resource Mgmt Office', code: 'HRMO', is_active: true },
    { id: 3, name: 'City Engineering Office', code: 'CEO', is_active: true },
    { id: 4, name: 'City Planning Office', code: 'CPO', is_active: true },
    { id: 5, name: 'City Treasurer / Finance', code: 'CTF', is_active: true },
    { id: 6, name: 'City Accounting Office', code: 'CAO', is_active: true },
    { id: 7, name: 'City Budget Office', code: 'CBO', is_active: true },
    { id: 8, name: 'City Assessor Office', code: 'CASS', is_active: true },
    { id: 9, name: 'City Health Office', code: 'CHO', is_active: true },
    { id: 10, name: 'City Social Welfare Office', code: 'CSWO', is_active: true },
    { id: 11, name: 'Admin Office', code: 'ADMIN', is_active: true },
    { id: 12, name: 'City Agriculture Office', code: 'CAGR', is_active: true },
];

// ── Mock Document Types ─────────────────────────────────────────────
export const mockDocumentTypes: DocumentType[] = [
    { id: 1, name: 'Executive Order', arta_processing_days: 7, is_active: true },
    { id: 2, name: 'Memorandum', arta_processing_days: 3, is_active: true },
    { id: 3, name: 'Travel Order', arta_processing_days: 7, is_active: true },
    { id: 4, name: 'Leave Application', arta_processing_days: 3, is_active: true },
    { id: 5, name: 'Procurement Request', arta_processing_days: 20, is_active: true },
    { id: 6, name: 'Legal Document', arta_processing_days: 20, is_active: true },
    { id: 7, name: 'Endorsement Letter', arta_processing_days: 3, is_active: true },
    { id: 8, name: 'Permit Application', arta_processing_days: 7, is_active: true },
    { id: 9, name: 'Correspondence', arta_processing_days: 3, is_active: true },
    { id: 10, name: 'Report', arta_processing_days: 7, is_active: true },
];

// ── Mock Documents ──────────────────────────────────────────────────
export const mockDocuments: Document[] = [
    {
        id: 1,
        reference_number: 'TNG-2026-0004',
        tracking_number: 'TRK-20260702-001',
        title: 'Executive Order No. 12 – Mati City Clean Drive',
        document_type: mockDocumentTypes[0],
        department: mockDepartments[0],
        submitted_by: 'Admin Office',
        current_holder: 'City Engineering Office',
        current_holder_department: 'City Engineering Office',
        classification: 'normal',
        status: 'endorsed',
        contact_number: '09181234567',
        step_progress: 2,
        total_steps: 5,
        arta_due_date: '2026-07-09',
        arta_days_left: 6,
        arta_threshold: 7,
        submitted_at: '2026-07-02T10:37:00',
        created_at: '2026-07-02T10:37:00',
        updated_at: '2026-07-02T10:37:00',
        sender: 'Admin Office',
        version: 'v1.0',
    },
    {
        id: 2,
        reference_number: 'TNG-2026-0006',
        tracking_number: 'TRK-20260703-002',
        title: 'Memorandum on Staff Rotation',
        document_type: mockDocumentTypes[1],
        department: mockDepartments[1],
        submitted_by: 'HR Department',
        current_holder: 'Receiving Office',
        classification: 'normal',
        status: 'submitted',
        step_progress: 1,
        total_steps: 5,
        arta_days_left: 3,
        arta_threshold: 3,
        submitted_at: '2026-07-03T09:15:00',
        created_at: '2026-07-03T09:15:00',
        updated_at: '2026-07-03T09:15:00',
    },
    {
        id: 3,
        reference_number: 'TNG-2026-0002',
        tracking_number: 'TRK-20260701-003',
        title: 'Travel Order – Engineer Site Inspection',
        document_type: mockDocumentTypes[2],
        department: mockDepartments[2],
        submitted_by: 'Engr. Pedro Lim',
        current_holder: 'Department Head',
        classification: 'normal',
        status: 'accepted',
        step_progress: 4,
        total_steps: 5,
        arta_days_left: 1,
        arta_threshold: 7,
        submitted_at: '2026-07-01T08:00:00',
        created_at: '2026-07-01T08:00:00',
        updated_at: '2026-07-01T08:00:00',
    },
    {
        id: 4,
        reference_number: 'TNG-2026-0005',
        tracking_number: 'TRK-20260630-004',
        title: 'Leave Application – Pedro Garcia',
        document_type: mockDocumentTypes[3],
        department: mockDepartments[4],
        submitted_by: 'Pedro Garcia',
        current_holder: 'Receiving Office',
        classification: 'normal',
        status: 'returned',
        step_progress: 2,
        total_steps: 5,
        arta_days_left: 0,
        arta_threshold: 3,
        submitted_at: '2026-06-30T14:20:00',
        created_at: '2026-06-30T14:20:00',
        updated_at: '2026-06-30T14:20:00',
    },
    {
        id: 5,
        reference_number: 'TNG-2026-0001',
        tracking_number: 'TRK-20260628-005',
        title: 'Leave Application – Juan Dela Cruz',
        document_type: mockDocumentTypes[3],
        department: mockDepartments[1],
        submitted_by: 'Juan Dela Cruz',
        current_holder: 'Completed',
        classification: 'normal',
        status: 'completed',
        step_progress: 5,
        total_steps: 5,
        arta_days_left: 3,
        arta_threshold: 3,
        submitted_at: '2026-06-28T11:00:00',
        completed_at: '2026-06-30T16:00:00',
        created_at: '2026-06-28T11:00:00',
        updated_at: '2026-06-30T16:00:00',
    },
    {
        id: 6,
        reference_number: 'TNG-2026-0003',
        tracking_number: 'TRK-20260621-006',
        title: 'Procurement Request – Office Supplies',
        document_type: mockDocumentTypes[4],
        department: mockDepartments[1],
        submitted_by: 'Dr. Ana Reyes',
        current_holder: 'Receiving Office',
        classification: 'normal',
        status: 'submitted',
        step_progress: 1,
        total_steps: 5,
        arta_days_left: -5,
        arta_threshold: 20,
        submitted_at: '2026-06-21T09:30:00',
        created_at: '2026-06-21T09:30:00',
        updated_at: '2026-06-21T09:30:00',
    },
];

// ── Mock Users ──────────────────────────────────────────────────────
export const mockUsers: TrackngoUser[] = [
    { id: 1, name: 'Admin User', email: 'admin@trackngo.gov.ph', role: 'admin', department: mockDepartments[0], is_active: true },
    { id: 2, name: 'Hon. Michelle Santos', email: 'mayor@trackngo.gov.ph', role: 'mayor', department: mockDepartments[0], is_active: true },
    { id: 3, name: 'Engr. Pedro Lim', email: 'depthead@trackngo.gov.ph', role: 'department_head', department: mockDepartments[2], is_active: true },
    { id: 4, name: 'Maria Clara', email: 'receiving@trackngo.gov.ph', role: 'receiving', department: mockDepartments[0], is_active: true },
    { id: 5, name: 'Carlos Mendoza', email: 'cart@trackngo.gov.ph', role: 'cart', department: mockDepartments[0], is_active: true },
    { id: 6, name: 'Juan Dela Cruz', email: 'juan@example.com', role: 'client', is_active: true },
];

// ── Mock Dashboard Stats ────────────────────────────────────────────
export const mockDashboardStats: DashboardStats = {
    total_documents: 13,
    completed: 5,
    in_progress: 4,
    returned: 2,
    pending: 2,
    escalated: 1,
    completion_rate: 38,
};

// ── Mock Bottleneck Data ────────────────────────────────────────────
export const mockBottlenecks: BottleneckData[] = [
    { stage: 'Receiving', count: 3 },
    { stage: 'Dept Head', count: 5 },
    { stage: 'CART', count: 0 },
    { stage: 'Mayor', count: 2 },
];

// ── Mock Status Distribution ────────────────────────────────────────
export const mockStatusDistribution: StatusDistribution[] = [
    { label: 'Completed', value: 79, color: '#2563eb' },
    { label: 'In Progress', value: 13, color: '#f59e0b' },
    { label: 'Returned', value: 8, color: '#ef4444' },
];

// ── Mock Routing Slips ──────────────────────────────────────────────
export const mockRoutingSlips: RoutingSlip[] = [
    {
        id: 1,
        document_id: 1,
        document: mockDocuments[0],
        from_user: 'Maria Clara',
        to_user: 'Engr. Pedro Lim',
        from_department: 'Receiving Office',
        to_department: 'City Engineering Office',
        instruction: 'For review and endorsement of Executive Order No. 12',
        action: 'forward',
        status: 'completed',
        created_at: '2026-07-02T10:45:00',
    },
    {
        id: 2,
        document_id: 3,
        document: mockDocuments[2],
        from_user: 'Engr. Pedro Lim',
        to_user: 'Hon. Michelle Santos',
        from_department: 'City Engineering Office',
        to_department: 'Office of the Mayor',
        instruction: 'Endorsed for final approval – travel order for site inspection',
        action: 'endorse',
        status: 'active',
        created_at: '2026-07-01T14:30:00',
    },
    {
        id: 3,
        document_id: 4,
        document: mockDocuments[3],
        from_user: 'Engr. Pedro Lim',
        to_user: 'Maria Clara',
        from_department: 'City Engineering Office',
        to_department: 'Receiving Office',
        instruction: 'Returned – incomplete supporting documents',
        action: 'return',
        status: 'completed',
        created_at: '2026-07-01T11:00:00',
    },
];

// ── Mock Audit Trail ────────────────────────────────────────────────
export const mockAuditTrail: AuditTrailEntry[] = [
    { id: 1, user: 'Maria Clara', user_role: 'receiving', department: 'Receiving Office', document_ref: 'TNG-2026-0004', action: 'Document Registered', description: 'Registered Executive Order No. 12 and generated QR code', ip_address: '192.168.1.101', timestamp: '2026-07-02T10:37:00' },
    { id: 2, user: 'Maria Clara', user_role: 'receiving', department: 'Receiving Office', document_ref: 'TNG-2026-0004', action: 'Document Forwarded', description: 'Forwarded to City Engineering Office for review', ip_address: '192.168.1.101', timestamp: '2026-07-02T10:45:00' },
    { id: 3, user: 'Engr. Pedro Lim', user_role: 'department_head', department: 'City Engineering Office', document_ref: 'TNG-2026-0004', action: 'Document Endorsed', description: 'Reviewed and endorsed for Mayor approval', ip_address: '192.168.1.105', timestamp: '2026-07-02T14:20:00' },
    { id: 4, user: 'Admin User', user_role: 'admin', department: 'Admin Office', action: 'User Login', description: 'Logged in to the system', ip_address: '192.168.1.100', timestamp: '2026-07-02T08:00:00' },
    { id: 5, user: 'Carlos Mendoza', user_role: 'cart', department: 'CART Office', document_ref: 'TNG-2026-0003', action: 'Escalation Triggered', description: 'Document exceeded 20-day ARTA processing period', ip_address: '192.168.1.110', timestamp: '2026-07-02T09:00:00' },
    { id: 6, user: 'Maria Clara', user_role: 'receiving', department: 'Receiving Office', document_ref: 'TNG-2026-0006', action: 'Document Registered', description: 'Registered Memorandum on Staff Rotation', ip_address: '192.168.1.101', timestamp: '2026-07-03T09:15:00' },
    { id: 7, user: 'Hon. Michelle Santos', user_role: 'mayor', department: 'Office of the Mayor', document_ref: 'TNG-2026-0001', action: 'Document Approved', description: 'Final approval granted for Leave Application', ip_address: '192.168.1.102', timestamp: '2026-06-30T16:00:00' },
    { id: 8, user: 'Engr. Pedro Lim', user_role: 'department_head', department: 'City Engineering Office', document_ref: 'TNG-2026-0005', action: 'Document Returned', description: 'Returned – incomplete supporting documents', ip_address: '192.168.1.105', timestamp: '2026-07-01T11:00:00' },
];

// ── Mock ARTA Escalations ───────────────────────────────────────────
export const mockEscalations: ArtaEscalation[] = [
    {
        id: 1,
        document_id: 6,
        document: mockDocuments[5],
        arta_threshold: 20,
        days_elapsed: 25,
        escalation_level: 'overdue',
        notified_user: 'Carlos Mendoza',
        notification_sent: true,
        resolved: false,
        escalated_at: '2026-07-16T09:00:00',
    },
    {
        id: 2,
        document_id: 4,
        document: mockDocuments[3],
        arta_threshold: 3,
        days_elapsed: 4,
        escalation_level: 'warning',
        notified_user: 'Carlos Mendoza',
        notification_sent: true,
        resolved: false,
        escalated_at: '2026-07-04T09:00:00',
    },
];

// ── Mock SMS Notifications ──────────────────────────────────────────
export const mockSmsNotifications: SmsNotification[] = [
    { id: 1, document_ref: 'TNG-2026-0004', recipient_name: 'Admin Office', mobile_number: '09181234567', message: 'Your document TNG-2026-0004 has been submitted and is now being processed.', status: 'sent', sent_at: '2026-07-02T10:38:00', created_at: '2026-07-02T10:38:00' },
    { id: 2, document_ref: 'TNG-2026-0004', recipient_name: 'Engr. Pedro Lim', mobile_number: '09182345678', message: 'Document TNG-2026-0004 has been forwarded to your office for review.', status: 'sent', sent_at: '2026-07-02T10:46:00', created_at: '2026-07-02T10:46:00' },
    { id: 3, document_ref: 'TNG-2026-0001', recipient_name: 'Juan Dela Cruz', mobile_number: '09183456789', message: 'Your document TNG-2026-0001 has been approved and completed.', status: 'sent', sent_at: '2026-06-30T16:05:00', created_at: '2026-06-30T16:05:00' },
    { id: 4, document_ref: 'TNG-2026-0005', recipient_name: 'Pedro Garcia', mobile_number: '09184567890', message: 'Your document TNG-2026-0005 has been returned. Please check for incomplete requirements.', status: 'sent', sent_at: '2026-07-01T11:05:00', created_at: '2026-07-01T11:05:00' },
    { id: 5, document_ref: 'TNG-2026-0003', recipient_name: 'Dr. Ana Reyes', mobile_number: '09185678901', message: 'ALERT: Your document TNG-2026-0003 has exceeded the ARTA processing deadline. It has been escalated.', status: 'sent', sent_at: '2026-07-02T09:01:00', created_at: '2026-07-02T09:01:00' },
    { id: 6, document_ref: 'TNG-2026-0006', recipient_name: 'HR Department', mobile_number: '09186789012', message: 'Your document TNG-2026-0006 has been submitted and is now being processed.', status: 'pending', created_at: '2026-07-03T09:16:00' },
];
